POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NWE2YjhjMThkNzUwZDM2MGIwNjQ1NGEiLCJpYXQiOjE3MDU0Mjc3MTQsImV4cCI6MTcwNTQzMTMxNH0.JRpjVKkzRSSj9qgCT5iDal3dsXT0ZIId8285_EAfuTU

{
    "content": "Blog about the life?",
    "important": false
}

